server:
  port: 8888
  servlet:
    context-path: /cms
spring:
  banner:
    charset: UTF-8
  application:
    name: SpringBootCMS
  freemarker:
    request-context-attribute: request
    suffix: .html
    content-type: text/html
    enabled: true
    cache: false
    charset: UTF-8
    allow-request-override: false
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    template-loader-path: classpath:/templates/
    settings:
      number_format: 0.##
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 60000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  file:
    winPath: D:\temp\java\
    linuxPath: /home/moshow/upload-files/
  cache:
    type: caffeine
    cache-names:
      - cache-article
      - cache-activity
      - cache-form
      - cache-page
      - cache-channel
    caffeine:
      spec: maximumSize=500,expireAfterWrite=600s
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.softdev.cms.entity
  configuration:
    map-underscore-to-camel-case: true
